### ISSUE TITLE
tty0tty.c:847:18: error: incompatible pointer type to write() (debian package only)

### ISSUE THREAD

**Issue by epsilonrt** [lcgamboa/tty0tty#26]
Debian package installation fails on latest GCC versions with write() function prototype issue:

```
epsilonrt@nanopineo:~/src/tty0tty/module$ gcc --version
gcc (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

epsilonrt@nanopineo:~$ sudo apt install tty0tty-dkms
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait
Les paquets supplémentaires suivants seront installés :
  bzip2 dkms dpkg-dev patch xz-utils
Paquets suggérés :
  bzip2-doc menu debian-keyring ed diffutils-doc
Paquets recommandés :
  fakeroot build-essential libalgorithm-merge-perl
Les NOUVEAUX paquets suivants seront installés :
  bzip2 dkms dpkg-dev patch tty0tty-dkms xz-utils
[...]
Paramétrage de dkms (3.0.10-8+deb12u1) ...
Paramétrage de tty0tty-dkms (1.41) ...
Loading new tty0tty-1.41 DKMS files...
Deprecated feature: REMAKE_INITRD (/usr/src/tty0tty-1.41/dkms.conf)
Building for 6.12.23-current-sunxi
Building initial module for 6.12.23-current-sunxi
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/tty0tty/1.41/source/dkms.conf)
Error! Bad return status for module build on kernel: 6.12.23-current-sunxi (armv7l)
Consult /var/lib/dkms/tty0tty/1.41/build/make.log for more information.
dpkg: erreur de traitement du paquet tty0tty-dkms (--configure) :
 le sous-processus paquet tty0tty-dkms script post-installation installé a renvoyé un état de sortie d'erreur 10
Traitement des actions différées (« triggers ») pour man-db (2.11.2-2) ...
Des erreurs ont été rencontrées pendant l'exécution :
 tty0tty-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

epsilonrt@nanopineo:~$ cat  /var/lib/dkms/tty0tty/1.41/build/make.log
DKMS make.log for tty0tty-1.41 for kernel 6.12.23-current-sunxi (armv7l)
mar. 06 mai 2025 08:52:41 CEST
make : on entre dans le répertoire « /usr/src/linux-headers-6.12.23-current-sunxi »
  CC [M]  /var/lib/dkms/tty0tty/1.41/build/tty0tty.o
/var/lib/dkms/tty0tty/1.41/build/tty0tty.c:847:18: error: initialization of ‘ssize_t (*)(struct tty_struct *, const u8 *, size_t)’ {aka ‘int (*)(struct tty_struct *, const unsigned char *, unsigned int)’} from incompatible pointer type ‘int (*)(struct tty_struct *, const unsigned char *, int)’ [-Werror=incompatible-pointer-types]
  847 |         .write = tty0tty_write,
      |                  ^~~~~~~~~~~~~
/var/lib/dkms/tty0tty/1.41/build/tty0tty.c:847:18: note: (near initialization for ‘serial_ops.write’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:229 : /var/lib/dkms/tty0tty/1.41/build/tty0tty.o] Erreur 1
make[1]: *** [/usr/src/linux-headers-6.12.23-current-sunxi/Makefile:1946 : /var/lib/dkms/tty0tty/1.41/build] Erreur 2
make: *** [Makefile:224 : __sub-make] Erreur 2
make : on quitte le répertoire « /usr/src/linux-headers-6.12.23-current-sunxi »
```

But it works with dkms-install script:

```
epsilonrt@nanopineo:~/src/tty0tty/module$ sudo ./dkms-install.sh
[sudo] Mot de passe de epsilonrt :
About to run dkms install steps...
Deprecated feature: REMAKE_INITRD (/usr/src/tty0tty-1.4/dkms.conf)
Creating symlink /var/lib/dkms/tty0tty/1.4/source -> /usr/src/tty0tty-1.4
Sign command: /lib/modules/6.12.23-current-sunxi/build/scripts/sign-file
Binary /lib/modules/6.12.23-current-sunxi/build/scripts/sign-file not found, modules won't be signed
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/tty0tty/1.4/source/dkms.conf)

Building module:
Cleaning build area...
'make' -j4 KVERSION=6.12.23-current-sunxi KERNELDIR=/lib/modules/6.12.23-current-sunxi/build......
Cleaning build area...
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/tty0tty/1.4/source/dkms.conf)

tty0tty.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.12.23-current-sunxi/updates/dkms/
depmod.....
Finished running dkms install steps.
echo "tty0tty" > /etc/modules-load.d/tty0tty.conf
cp 99-tty0tty.rules  /etc/udev/rules.d/
udevadm control --reload-rules && udevadm trigger
chown root:root /etc/udev/rules.d/99-tty0tty.rules

epsilonrt@nanopineo:~/src/tty0tty/module$ dmesg | tail
[...]
[ 2710.600289] tty0tty: loading out-of-tree module taints kernel.
[ 2710.605285] tty0tty null modem driver v1.4
```

So I need to check the compilation options for the debian package.
